<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250204190415 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE menu_menu (menu_source INT NOT NULL, menu_target INT NOT NULL, PRIMARY KEY(menu_source, menu_target))');
        $this->addSql('CREATE INDEX IDX_B54ACADD8CCD27AB ON menu_menu (menu_source)');
        $this->addSql('CREATE INDEX IDX_B54ACADD95287724 ON menu_menu (menu_target)');
        $this->addSql('ALTER TABLE menu_menu ADD CONSTRAINT FK_B54ACADD8CCD27AB FOREIGN KEY (menu_source) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu_menu ADD CONSTRAINT FK_B54ACADD95287724 FOREIGN KEY (menu_target) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE api_token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE asiento ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE boleto ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE boleto_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE bus ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE cliente ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE empresa ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE factura ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE fdn ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE localidad ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT fk_7d053a93bf396750');
        $this->addSql('ALTER TABLE menu ADD posicion SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu ADD nombre VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE menu ADD nota TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE menu ADD parent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93727ACA70 FOREIGN KEY (parent_id) REFERENCES menu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_7D053A93727ACA70 ON menu (parent_id)');
        $this->addSql('ALTER TABLE pais ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE parada_intermedia ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE permiso ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE piloto ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE recorrido_asiento_precio ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE salida ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE salida_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE venta ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE menu_menu DROP CONSTRAINT FK_B54ACADD8CCD27AB');
        $this->addSql('ALTER TABLE menu_menu DROP CONSTRAINT FK_B54ACADD95287724');
        $this->addSql('DROP TABLE menu_menu');
        $this->addSql('ALTER TABLE factura ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE recorrido_asiento_precio ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE salida_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE piloto ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT FK_7D053A93727ACA70');
        $this->addSql('DROP INDEX IDX_7D053A93727ACA70');
        $this->addSql('ALTER TABLE menu DROP posicion');
        $this->addSql('ALTER TABLE menu DROP nombre');
        $this->addSql('ALTER TABLE menu DROP nota');
        $this->addSql('ALTER TABLE menu DROP status');
        $this->addSql('ALTER TABLE menu DROP parent_id');
        $this->addSql('ALTER TABLE menu ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT fk_7d053a93bf396750 FOREIGN KEY (id) REFERENCES fdn (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pais ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE api_token ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE bus ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE fdn ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE venta ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE asiento ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cliente ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE boleto ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE parada_intermedia ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE localidad ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE salida ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE permiso ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE boleto_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE empresa ALTER id DROP IDENTITY');
    }
}
