<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311215016 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE entity_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_class VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_844909DB41BF2C66 ON entity_configuration (entity_class)');
        $this->addSql('CREATE TABLE form_field_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field_name VARCHAR(255) NOT NULL, position INT NOT NULL, group_label VARCHAR(255) DEFAULT NULL, input_props JSON DEFAULT NULL, entity_config_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9489E81C52A5B3AF ON form_field_config (entity_config_id)');
        $this->addSql('CREATE TABLE list_field_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field_name VARCHAR(255) NOT NULL, position INT NOT NULL, visible BOOLEAN NOT NULL, filterable BOOLEAN NOT NULL, label VARCHAR(255) DEFAULT NULL, entity_config_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_842B466552A5B3AF ON list_field_config (entity_config_id)');
        $this->addSql('ALTER TABLE form_field_config ADD CONSTRAINT FK_9489E81C52A5B3AF FOREIGN KEY (entity_config_id) REFERENCES entity_configuration (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE list_field_config ADD CONSTRAINT FK_842B466552A5B3AF FOREIGN KEY (entity_config_id) REFERENCES entity_configuration (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE form_field_config DROP CONSTRAINT FK_9489E81C52A5B3AF');
        $this->addSql('ALTER TABLE list_field_config DROP CONSTRAINT FK_842B466552A5B3AF');
        $this->addSql('DROP TABLE entity_configuration');
        $this->addSql('DROP TABLE form_field_config');
        $this->addSql('DROP TABLE list_field_config');
    }
}
