<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250322184810 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE role_role (role_source INT NOT NULL, role_target INT NOT NULL, PRIMARY KEY(role_source, role_target))');
        $this->addSql('CREATE INDEX IDX_E9D6F8FEF4AC9EC2 ON role_role (role_source)');
        $this->addSql('CREATE INDEX IDX_E9D6F8FEED49CE4D ON role_role (role_target)');
        $this->addSql('ALTER TABLE role_role ADD CONSTRAINT FK_E9D6F8FEF4AC9EC2 FOREIGN KEY (role_source) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_role ADD CONSTRAINT FK_E9D6F8FEED49CE4D FOREIGN KEY (role_target) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE role_role DROP CONSTRAINT FK_E9D6F8FEF4AC9EC2');
        $this->addSql('ALTER TABLE role_role DROP CONSTRAINT FK_E9D6F8FEED49CE4D');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_role');
    }
}
