<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260322051158 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE collection_field_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT NULL, position INT NOT NULL, visible BOOLEAN DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, attrs JSON DEFAULT NULL, sortable BOOLEAN DEFAULT NULL, filterable BOOLEAN DEFAULT NULL, entity_config_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64EDBA5452A5B3AF ON collection_field_config (entity_config_id)');
        $this->addSql('ALTER TABLE collection_field_config ADD CONSTRAINT FK_64EDBA5452A5B3AF FOREIGN KEY (entity_config_id) REFERENCES entity_configuration (id)');
        $this->addSql('ALTER TABLE list_field_config DROP CONSTRAINT fk_842b466552a5b3af');
        $this->addSql('DROP TABLE list_field_config');
        $this->addSql('ALTER TABLE form_field_config ALTER entity_config_id DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE list_field_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field VARCHAR(255) NOT NULL, "position" INT NOT NULL, visible BOOLEAN DEFAULT NULL, sortable BOOLEAN NOT NULL, label VARCHAR(255) DEFAULT NULL, entity_config_id INT NOT NULL, type VARCHAR(255) DEFAULT NULL, attrs JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_842b466552a5b3af ON list_field_config (entity_config_id)');
        $this->addSql('ALTER TABLE list_field_config ADD CONSTRAINT fk_842b466552a5b3af FOREIGN KEY (entity_config_id) REFERENCES entity_configuration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collection_field_config DROP CONSTRAINT FK_64EDBA5452A5B3AF');
        $this->addSql('DROP TABLE collection_field_config');
        $this->addSql('ALTER TABLE form_field_config ALTER entity_config_id SET NOT NULL');
    }
}
