<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504165145 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE action ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE action DROP status');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C926BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_47CC8C926BF700BD ON action (status_id)');
        $this->addSql('ALTER TABLE boleto ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto DROP status');
        $this->addSql('ALTER TABLE boleto ADD CONSTRAINT FK_462E6E256BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_462E6E256BF700BD ON boleto (status_id)');
        $this->addSql('ALTER TABLE bus ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE bus DROP status');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B696BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_2F566B696BF700BD ON bus (status_id)');
        $this->addSql('ALTER TABLE cliente ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cliente DROP status');
        $this->addSql('ALTER TABLE cliente ADD CONSTRAINT FK_F41C9B256BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_F41C9B256BF700BD ON cliente (status_id)');
        $this->addSql('ALTER TABLE empresa ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE empresa DROP status');
        $this->addSql('ALTER TABLE empresa ADD CONSTRAINT FK_B8D75A506BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_B8D75A506BF700BD ON empresa (status_id)');
        $this->addSql('ALTER TABLE enclave ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE enclave DROP status');
        $this->addSql('ALTER TABLE enclave ADD CONSTRAINT FK_D4D67D806BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_D4D67D806BF700BD ON enclave (status_id)');
        $this->addSql('ALTER TABLE factura ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE factura DROP status');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA0096BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_F9EBA0096BF700BD ON factura (status_id)');
        $this->addSql('ALTER TABLE menu ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu DROP status');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A936BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_7D053A936BF700BD ON menu (status_id)');
        $this->addSql('ALTER TABLE parada ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE parada DROP status');
        $this->addSql('ALTER TABLE parada ADD CONSTRAINT FK_ADB5C4F26BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_ADB5C4F26BF700BD ON parada (status_id)');
        $this->addSql('ALTER TABLE permiso ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE permiso DROP status');
        $this->addSql('ALTER TABLE permiso ADD CONSTRAINT FK_FD7AAB9E6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_FD7AAB9E6BF700BD ON permiso (status_id)');
        $this->addSql('ALTER TABLE piloto ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE piloto DROP status');
        $this->addSql('ALTER TABLE piloto ADD CONSTRAINT FK_8AE7BDC36BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_8AE7BDC36BF700BD ON piloto (status_id)');
        $this->addSql('ALTER TABLE recorrido ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE recorrido DROP status');
        $this->addSql('ALTER TABLE recorrido ADD CONSTRAINT FK_3A1543A86BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_3A1543A86BF700BD ON recorrido (status_id)');
        $this->addSql('ALTER TABLE salida ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE salida DROP status');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT FK_95F4C7486BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_95F4C7486BF700BD ON salida (status_id)');
        $this->addSql('ALTER TABLE taxon ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE taxon DROP status');
        $this->addSql('ALTER TABLE taxon ADD CONSTRAINT FK_5B6723AB6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_5B6723AB6BF700BD ON taxon (status_id)');
        $this->addSql('ALTER TABLE "user" ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" DROP status');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6496BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_8D93D6496BF700BD ON "user" (status_id)');
        $this->addSql('ALTER TABLE venta ADD status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE venta DROP status');
        $this->addSql('ALTER TABLE venta ADD CONSTRAINT FK_8FE7EE556BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('CREATE INDEX IDX_8FE7EE556BF700BD ON venta (status_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE status');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C926BF700BD');
        $this->addSql('DROP INDEX IDX_47CC8C926BF700BD');
        $this->addSql('ALTER TABLE action ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE action DROP status_id');
        $this->addSql('ALTER TABLE boleto DROP CONSTRAINT FK_462E6E256BF700BD');
        $this->addSql('DROP INDEX IDX_462E6E256BF700BD');
        $this->addSql('ALTER TABLE boleto ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE boleto DROP status_id');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT FK_2F566B696BF700BD');
        $this->addSql('DROP INDEX IDX_2F566B696BF700BD');
        $this->addSql('ALTER TABLE bus ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE bus DROP status_id');
        $this->addSql('ALTER TABLE cliente DROP CONSTRAINT FK_F41C9B256BF700BD');
        $this->addSql('DROP INDEX IDX_F41C9B256BF700BD');
        $this->addSql('ALTER TABLE cliente ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cliente DROP status_id');
        $this->addSql('ALTER TABLE empresa DROP CONSTRAINT FK_B8D75A506BF700BD');
        $this->addSql('DROP INDEX IDX_B8D75A506BF700BD');
        $this->addSql('ALTER TABLE empresa ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE empresa DROP status_id');
        $this->addSql('ALTER TABLE enclave DROP CONSTRAINT FK_D4D67D806BF700BD');
        $this->addSql('DROP INDEX IDX_D4D67D806BF700BD');
        $this->addSql('ALTER TABLE enclave ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE enclave DROP status_id');
        $this->addSql('ALTER TABLE factura DROP CONSTRAINT FK_F9EBA0096BF700BD');
        $this->addSql('DROP INDEX IDX_F9EBA0096BF700BD');
        $this->addSql('ALTER TABLE factura ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE factura DROP status_id');
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT FK_7D053A936BF700BD');
        $this->addSql('DROP INDEX IDX_7D053A936BF700BD');
        $this->addSql('ALTER TABLE menu ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE menu DROP status_id');
        $this->addSql('ALTER TABLE parada DROP CONSTRAINT FK_ADB5C4F26BF700BD');
        $this->addSql('DROP INDEX IDX_ADB5C4F26BF700BD');
        $this->addSql('ALTER TABLE parada ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE parada DROP status_id');
        $this->addSql('ALTER TABLE permiso DROP CONSTRAINT FK_FD7AAB9E6BF700BD');
        $this->addSql('DROP INDEX IDX_FD7AAB9E6BF700BD');
        $this->addSql('ALTER TABLE permiso ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE permiso DROP status_id');
        $this->addSql('ALTER TABLE piloto DROP CONSTRAINT FK_8AE7BDC36BF700BD');
        $this->addSql('DROP INDEX IDX_8AE7BDC36BF700BD');
        $this->addSql('ALTER TABLE piloto ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE piloto DROP status_id');
        $this->addSql('ALTER TABLE recorrido DROP CONSTRAINT FK_3A1543A86BF700BD');
        $this->addSql('DROP INDEX IDX_3A1543A86BF700BD');
        $this->addSql('ALTER TABLE recorrido ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE recorrido DROP status_id');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT FK_95F4C7486BF700BD');
        $this->addSql('DROP INDEX IDX_95F4C7486BF700BD');
        $this->addSql('ALTER TABLE salida ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE salida DROP status_id');
        $this->addSql('ALTER TABLE taxon DROP CONSTRAINT FK_5B6723AB6BF700BD');
        $this->addSql('DROP INDEX IDX_5B6723AB6BF700BD');
        $this->addSql('ALTER TABLE taxon ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE taxon DROP status_id');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6496BF700BD');
        $this->addSql('DROP INDEX IDX_8D93D6496BF700BD');
        $this->addSql('ALTER TABLE "user" ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" DROP status_id');
        $this->addSql('ALTER TABLE venta DROP CONSTRAINT FK_8FE7EE556BF700BD');
        $this->addSql('DROP INDEX IDX_8FE7EE556BF700BD');
        $this->addSql('ALTER TABLE venta ADD status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE venta DROP status_id');
    }
}
