<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240429061959 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agencia (alias VARCHAR(10) NOT NULL, legacy_id INT DEFAULT NULL, id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expira TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, token VARCHAR(68) NOT NULL, scopes JSON NOT NULL, activo BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7BA2F5EBDB38439E ON api_token (usuario_id)');
        $this->addSql('CREATE TABLE asiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero SMALLINT NOT NULL, clase VARCHAR(1) DEFAULT NULL, bus_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_71D6D35C2546731D ON asiento (bus_id)');
        $this->addSql('CREATE TABLE boleto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, estado SMALLINT NOT NULL, status SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, precio DOUBLE PRECISION DEFAULT NULL, cliente_id INT NOT NULL, asiento_id INT NOT NULL, salida_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_462E6E25DE734E51 ON boleto (cliente_id)');
        $this->addSql('CREATE INDEX IDX_462E6E25C642F3A8 ON boleto (asiento_id)');
        $this->addSql('CREATE INDEX IDX_462E6E2526A36E51 ON boleto (salida_id)');
        $this->addSql('CREATE TABLE boleto_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descripcion TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tipo SMALLINT DEFAULT NULL, user_id INT DEFAULT NULL, boleto_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_83492590A76ED395 ON boleto_log (user_id)');
        $this->addSql('CREATE INDEX IDX_834925907F6F0A9B ON boleto_log (boleto_id)');
        $this->addSql('CREATE TABLE bus (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status SMALLINT NOT NULL, legacy_id INT DEFAULT NULL, codigo VARCHAR(15) DEFAULT NULL, precio_variacion_asiento_a DOUBLE PRECISION DEFAULT NULL, precio_variacion_asiento_b DOUBLE PRECISION DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, placa VARCHAR(25) DEFAULT NULL, empresa_id INT DEFAULT NULL, piloto_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2F566B69521E1991 ON bus (empresa_id)');
        $this->addSql('CREATE INDEX IDX_2F566B699AAD4A8D ON bus (piloto_id)');
        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status SMALLINT NOT NULL, legacy_id INT DEFAULT NULL, apellido VARCHAR(50) DEFAULT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(50) DEFAULT NULL, nit VARCHAR(20) DEFAULT NULL, telefono VARCHAR(15) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, dpi VARCHAR(15) DEFAULT NULL, localidad_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F41C9B2567707C89 ON cliente (localidad_id)');
        $this->addSql('CREATE TABLE empresa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status SMALLINT NOT NULL, legacy_id INT DEFAULT NULL, nombre_comercial VARCHAR(255) DEFAULT NULL, denominacion_social VARCHAR(255) DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(50) DEFAULT NULL, nit VARCHAR(20) DEFAULT NULL, telefono VARCHAR(15) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, localidad_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B8D75A5067707C89 ON empresa (localidad_id)');
        $this->addSql('CREATE TABLE enclave (nombre VARCHAR(255) DEFAULT NULL, nota TEXT DEFAULT NULL, status SMALLINT NOT NULL, email VARCHAR(50) DEFAULT NULL, telefono VARCHAR(15) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, localidad_id INT DEFAULT NULL, id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D4D67D8067707C89 ON enclave (localidad_id)');
        $this->addSql('CREATE TABLE estacion (alias VARCHAR(10) NOT NULL, legacy_id INT DEFAULT NULL, id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE factura (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status SMALLINT NOT NULL, dte VARCHAR(255) DEFAULT NULL, uuid UUID DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, serie VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE fdn (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE localidad (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, pais_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4F68E010C604D5C6 ON localidad (pais_id)');
        $this->addSql('CREATE TABLE pais (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE parada (nombre VARCHAR(255) DEFAULT NULL, nota TEXT DEFAULT NULL, status SMALLINT NOT NULL, enclave_id INT DEFAULT NULL, id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ADB5C4F27255AE3E ON parada (enclave_id)');
        $this->addSql('CREATE TABLE parada_recorrido (parada_id INT NOT NULL, recorrido_id INT NOT NULL, PRIMARY KEY(parada_id, recorrido_id))');
        $this->addSql('CREATE INDEX IDX_3E718638C49C376A ON parada_recorrido (parada_id)');
        $this->addSql('CREATE INDEX IDX_3E7186387A331FF ON parada_recorrido (recorrido_id)');
        $this->addSql('CREATE TABLE parada_intermedia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, posicion SMALLINT DEFAULT NULL, parada_id INT NOT NULL, recorrido_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B1A2EC88C49C376A ON parada_intermedia (parada_id)');
        $this->addSql('CREATE INDEX IDX_B1A2EC887A331FF ON parada_intermedia (recorrido_id)');
        $this->addSql('CREATE TABLE permiso (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nivel SMALLINT DEFAULT NULL, nombre VARCHAR(255) DEFAULT NULL, nota TEXT DEFAULT NULL, status SMALLINT NOT NULL, padre_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FD7AAB9E613CEC58 ON permiso (padre_id)');
        $this->addSql('CREATE TABLE permiso_user (permiso_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(permiso_id, user_id))');
        $this->addSql('CREATE INDEX IDX_DC9ED3516CEFAD37 ON permiso_user (permiso_id)');
        $this->addSql('CREATE INDEX IDX_DC9ED351A76ED395 ON permiso_user (user_id)');
        $this->addSql('CREATE TABLE piloto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status SMALLINT NOT NULL, legacy_id INT DEFAULT NULL, apellido VARCHAR(50) DEFAULT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(50) DEFAULT NULL, nit VARCHAR(20) DEFAULT NULL, telefono VARCHAR(15) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, licencia VARCHAR(255) DEFAULT NULL, licencia_vencimiento TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dpi VARCHAR(20) DEFAULT NULL, sexo VARCHAR(5) DEFAULT NULL, fecha_nacimiento TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, seguro_social VARCHAR(255) DEFAULT NULL, nacionalidad VARCHAR(255) DEFAULT NULL, localidad_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8AE7BDC367707C89 ON piloto (localidad_id)');
        $this->addSql('CREATE TABLE recorrido (nombre VARCHAR(255) DEFAULT NULL, nota TEXT DEFAULT NULL, status SMALLINT NOT NULL, tiempo TIME(0) WITHOUT TIME ZONE DEFAULT NULL, distancia DOUBLE PRECISION DEFAULT NULL, legacy_id INT DEFAULT NULL, inicio_id INT DEFAULT NULL, final_id INT DEFAULT NULL, id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3A1543A82D810B51 ON recorrido (inicio_id)');
        $this->addSql('CREATE INDEX IDX_3A1543A813D41B2D ON recorrido (final_id)');
        $this->addSql('CREATE TABLE recorrido_asiento_precio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, precio_asiento_a DOUBLE PRECISION DEFAULT NULL, precio_asiento_b DOUBLE PRECISION DEFAULT NULL, recorrido_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F52FC0C87A331FF ON recorrido_asiento_precio (recorrido_id)');
        $this->addSql('CREATE TABLE ruta (codigo VARCHAR(10) DEFAULT NULL, id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE salida (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status SMALLINT NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, bus_id INT DEFAULT NULL, recorrido_id INT NOT NULL, empresa_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_95F4C7482546731D ON salida (bus_id)');
        $this->addSql('CREATE INDEX IDX_95F4C7487A331FF ON salida (recorrido_id)');
        $this->addSql('CREATE INDEX IDX_95F4C748521E1991 ON salida (empresa_id)');
        $this->addSql('CREATE TABLE salida_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descripcion TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tipo VARCHAR(100) DEFAULT NULL, user_id INT DEFAULT NULL, salida_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F8A1C25AA76ED395 ON salida_log (user_id)');
        $this->addSql('CREATE INDEX IDX_F8A1C25A26A36E51 ON salida_log (salida_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status SMALLINT NOT NULL, legacy_id INT DEFAULT NULL, apellido VARCHAR(50) DEFAULT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(50) DEFAULT NULL, nit VARCHAR(20) DEFAULT NULL, telefono VARCHAR(15) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, localidad_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE INDEX IDX_8D93D64967707C89 ON "user" (localidad_id)');
        $this->addSql('CREATE TABLE venta (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status SMALLINT NOT NULL, precio DOUBLE PRECISION DEFAULT NULL, ida_id INT NOT NULL, regreso_id INT NOT NULL, user_id INT NOT NULL, factura_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8FE7EE55E811A2F8 ON venta (ida_id)');
        $this->addSql('CREATE INDEX IDX_8FE7EE55BA156E19 ON venta (regreso_id)');
        $this->addSql('CREATE INDEX IDX_8FE7EE55A76ED395 ON venta (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8FE7EE55F04F795F ON venta (factura_id)');
        $this->addSql('ALTER TABLE agencia ADD CONSTRAINT FK_EB6C2B99BF396750 FOREIGN KEY (id) REFERENCES fdn (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EBDB38439E FOREIGN KEY (usuario_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C2546731D FOREIGN KEY (bus_id) REFERENCES bus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boleto ADD CONSTRAINT FK_462E6E25DE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boleto ADD CONSTRAINT FK_462E6E25C642F3A8 FOREIGN KEY (asiento_id) REFERENCES asiento (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boleto ADD CONSTRAINT FK_462E6E2526A36E51 FOREIGN KEY (salida_id) REFERENCES salida (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boleto_log ADD CONSTRAINT FK_83492590A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boleto_log ADD CONSTRAINT FK_834925907F6F0A9B FOREIGN KEY (boleto_id) REFERENCES boleto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B69521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bus ADD CONSTRAINT FK_2F566B699AAD4A8D FOREIGN KEY (piloto_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cliente ADD CONSTRAINT FK_F41C9B2567707C89 FOREIGN KEY (localidad_id) REFERENCES localidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE empresa ADD CONSTRAINT FK_B8D75A5067707C89 FOREIGN KEY (localidad_id) REFERENCES localidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE enclave ADD CONSTRAINT FK_D4D67D8067707C89 FOREIGN KEY (localidad_id) REFERENCES localidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE enclave ADD CONSTRAINT FK_D4D67D80BF396750 FOREIGN KEY (id) REFERENCES fdn (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estacion ADD CONSTRAINT FK_32B2395FBF396750 FOREIGN KEY (id) REFERENCES fdn (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localidad ADD CONSTRAINT FK_4F68E010C604D5C6 FOREIGN KEY (pais_id) REFERENCES pais (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parada ADD CONSTRAINT FK_ADB5C4F27255AE3E FOREIGN KEY (enclave_id) REFERENCES enclave (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parada ADD CONSTRAINT FK_ADB5C4F2BF396750 FOREIGN KEY (id) REFERENCES fdn (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parada_recorrido ADD CONSTRAINT FK_3E718638C49C376A FOREIGN KEY (parada_id) REFERENCES parada (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parada_recorrido ADD CONSTRAINT FK_3E7186387A331FF FOREIGN KEY (recorrido_id) REFERENCES recorrido (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parada_intermedia ADD CONSTRAINT FK_B1A2EC88C49C376A FOREIGN KEY (parada_id) REFERENCES parada (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parada_intermedia ADD CONSTRAINT FK_B1A2EC887A331FF FOREIGN KEY (recorrido_id) REFERENCES recorrido (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permiso ADD CONSTRAINT FK_FD7AAB9E613CEC58 FOREIGN KEY (padre_id) REFERENCES permiso (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permiso_user ADD CONSTRAINT FK_DC9ED3516CEFAD37 FOREIGN KEY (permiso_id) REFERENCES permiso (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permiso_user ADD CONSTRAINT FK_DC9ED351A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE piloto ADD CONSTRAINT FK_8AE7BDC367707C89 FOREIGN KEY (localidad_id) REFERENCES localidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recorrido ADD CONSTRAINT FK_3A1543A82D810B51 FOREIGN KEY (inicio_id) REFERENCES parada (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recorrido ADD CONSTRAINT FK_3A1543A813D41B2D FOREIGN KEY (final_id) REFERENCES parada (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recorrido ADD CONSTRAINT FK_3A1543A8BF396750 FOREIGN KEY (id) REFERENCES fdn (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recorrido_asiento_precio ADD CONSTRAINT FK_F52FC0C87A331FF FOREIGN KEY (recorrido_id) REFERENCES recorrido (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ruta ADD CONSTRAINT FK_C3AEF08CBF396750 FOREIGN KEY (id) REFERENCES fdn (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT FK_95F4C7482546731D FOREIGN KEY (bus_id) REFERENCES bus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT FK_95F4C7487A331FF FOREIGN KEY (recorrido_id) REFERENCES recorrido (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE salida ADD CONSTRAINT FK_95F4C748521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE salida_log ADD CONSTRAINT FK_F8A1C25AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE salida_log ADD CONSTRAINT FK_F8A1C25A26A36E51 FOREIGN KEY (salida_id) REFERENCES salida (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64967707C89 FOREIGN KEY (localidad_id) REFERENCES localidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE venta ADD CONSTRAINT FK_8FE7EE55E811A2F8 FOREIGN KEY (ida_id) REFERENCES salida (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE venta ADD CONSTRAINT FK_8FE7EE55BA156E19 FOREIGN KEY (regreso_id) REFERENCES salida (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE venta ADD CONSTRAINT FK_8FE7EE55A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE venta ADD CONSTRAINT FK_8FE7EE55F04F795F FOREIGN KEY (factura_id) REFERENCES factura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE agencia DROP CONSTRAINT FK_EB6C2B99BF396750');
        $this->addSql('ALTER TABLE api_token DROP CONSTRAINT FK_7BA2F5EBDB38439E');
        $this->addSql('ALTER TABLE asiento DROP CONSTRAINT FK_71D6D35C2546731D');
        $this->addSql('ALTER TABLE boleto DROP CONSTRAINT FK_462E6E25DE734E51');
        $this->addSql('ALTER TABLE boleto DROP CONSTRAINT FK_462E6E25C642F3A8');
        $this->addSql('ALTER TABLE boleto DROP CONSTRAINT FK_462E6E2526A36E51');
        $this->addSql('ALTER TABLE boleto_log DROP CONSTRAINT FK_83492590A76ED395');
        $this->addSql('ALTER TABLE boleto_log DROP CONSTRAINT FK_834925907F6F0A9B');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT FK_2F566B69521E1991');
        $this->addSql('ALTER TABLE bus DROP CONSTRAINT FK_2F566B699AAD4A8D');
        $this->addSql('ALTER TABLE cliente DROP CONSTRAINT FK_F41C9B2567707C89');
        $this->addSql('ALTER TABLE empresa DROP CONSTRAINT FK_B8D75A5067707C89');
        $this->addSql('ALTER TABLE enclave DROP CONSTRAINT FK_D4D67D8067707C89');
        $this->addSql('ALTER TABLE enclave DROP CONSTRAINT FK_D4D67D80BF396750');
        $this->addSql('ALTER TABLE estacion DROP CONSTRAINT FK_32B2395FBF396750');
        $this->addSql('ALTER TABLE localidad DROP CONSTRAINT FK_4F68E010C604D5C6');
        $this->addSql('ALTER TABLE parada DROP CONSTRAINT FK_ADB5C4F27255AE3E');
        $this->addSql('ALTER TABLE parada DROP CONSTRAINT FK_ADB5C4F2BF396750');
        $this->addSql('ALTER TABLE parada_recorrido DROP CONSTRAINT FK_3E718638C49C376A');
        $this->addSql('ALTER TABLE parada_recorrido DROP CONSTRAINT FK_3E7186387A331FF');
        $this->addSql('ALTER TABLE parada_intermedia DROP CONSTRAINT FK_B1A2EC88C49C376A');
        $this->addSql('ALTER TABLE parada_intermedia DROP CONSTRAINT FK_B1A2EC887A331FF');
        $this->addSql('ALTER TABLE permiso DROP CONSTRAINT FK_FD7AAB9E613CEC58');
        $this->addSql('ALTER TABLE permiso_user DROP CONSTRAINT FK_DC9ED3516CEFAD37');
        $this->addSql('ALTER TABLE permiso_user DROP CONSTRAINT FK_DC9ED351A76ED395');
        $this->addSql('ALTER TABLE piloto DROP CONSTRAINT FK_8AE7BDC367707C89');
        $this->addSql('ALTER TABLE recorrido DROP CONSTRAINT FK_3A1543A82D810B51');
        $this->addSql('ALTER TABLE recorrido DROP CONSTRAINT FK_3A1543A813D41B2D');
        $this->addSql('ALTER TABLE recorrido DROP CONSTRAINT FK_3A1543A8BF396750');
        $this->addSql('ALTER TABLE recorrido_asiento_precio DROP CONSTRAINT FK_F52FC0C87A331FF');
        $this->addSql('ALTER TABLE ruta DROP CONSTRAINT FK_C3AEF08CBF396750');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT FK_95F4C7482546731D');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT FK_95F4C7487A331FF');
        $this->addSql('ALTER TABLE salida DROP CONSTRAINT FK_95F4C748521E1991');
        $this->addSql('ALTER TABLE salida_log DROP CONSTRAINT FK_F8A1C25AA76ED395');
        $this->addSql('ALTER TABLE salida_log DROP CONSTRAINT FK_F8A1C25A26A36E51');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64967707C89');
        $this->addSql('ALTER TABLE venta DROP CONSTRAINT FK_8FE7EE55E811A2F8');
        $this->addSql('ALTER TABLE venta DROP CONSTRAINT FK_8FE7EE55BA156E19');
        $this->addSql('ALTER TABLE venta DROP CONSTRAINT FK_8FE7EE55A76ED395');
        $this->addSql('ALTER TABLE venta DROP CONSTRAINT FK_8FE7EE55F04F795F');
        $this->addSql('DROP TABLE agencia');
        $this->addSql('DROP TABLE api_token');
        $this->addSql('DROP TABLE asiento');
        $this->addSql('DROP TABLE boleto');
        $this->addSql('DROP TABLE boleto_log');
        $this->addSql('DROP TABLE bus');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE empresa');
        $this->addSql('DROP TABLE enclave');
        $this->addSql('DROP TABLE estacion');
        $this->addSql('DROP TABLE factura');
        $this->addSql('DROP TABLE fdn');
        $this->addSql('DROP TABLE localidad');
        $this->addSql('DROP TABLE pais');
        $this->addSql('DROP TABLE parada');
        $this->addSql('DROP TABLE parada_recorrido');
        $this->addSql('DROP TABLE parada_intermedia');
        $this->addSql('DROP TABLE permiso');
        $this->addSql('DROP TABLE permiso_user');
        $this->addSql('DROP TABLE piloto');
        $this->addSql('DROP TABLE recorrido');
        $this->addSql('DROP TABLE recorrido_asiento_precio');
        $this->addSql('DROP TABLE ruta');
        $this->addSql('DROP TABLE salida');
        $this->addSql('DROP TABLE salida_log');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE venta');
    }
}
