<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251201021831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE icon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, icon VARCHAR(50) NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE icon_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE icon_category_icon (icon_category_id INT NOT NULL, icon_id INT NOT NULL, PRIMARY KEY (icon_category_id, icon_id))');
        $this->addSql('CREATE INDEX IDX_D0AECE2442B0E3D4 ON icon_category_icon (icon_category_id)');
        $this->addSql('CREATE INDEX IDX_D0AECE2454B9D732 ON icon_category_icon (icon_id)');
        $this->addSql('ALTER TABLE icon_category_icon ADD CONSTRAINT FK_D0AECE2442B0E3D4 FOREIGN KEY (icon_category_id) REFERENCES icon_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE icon_category_icon ADD CONSTRAINT FK_D0AECE2454B9D732 FOREIGN KEY (icon_id) REFERENCES icon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A9354B9D732 FOREIGN KEY (icon_id) REFERENCES icon (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE icon_category_icon DROP CONSTRAINT FK_D0AECE2442B0E3D4');
        $this->addSql('ALTER TABLE icon_category_icon DROP CONSTRAINT FK_D0AECE2454B9D732');
        $this->addSql('DROP TABLE icon');
        $this->addSql('DROP TABLE icon_category');
        $this->addSql('DROP TABLE icon_category_icon');
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT FK_7D053A9354B9D732');
    }
}
